package com.velasim.app;

import android.content.Context;

import org.json.JSONObject;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.UUID;

/**
 * One AVD = {@code <avdHome>/<avdId>.avd} holding
 * <pre>
 *   config.ini          hardware/image description (k=v, no spaces)
 *   AVD.conf            targetAbi/targetSdk tag
 *   emulator-user.ini   window.x / window.y / uuid
 *   share/              must exist, launcher refuses without it
 *   data/               guest /data mount
 *   vela_system.bin     copied from the installed system image
 *   vela_data.bin       copied likewise; guest /misc, writable
 *   hardware-qemu.ini   GENERATED by the launcher -- never authored here
 * </pre>
 *
 * <p>{@code image.sysdir.1} points at the unpacked system image directory and
 * {@code skin.path} at the extracted skin, so the emulator needs no search
 * path beyond <code>HOME/.vela/sdk</code>.
 *
 * <p>{@link #create} is idempotent: it rewrites config.ini and creates missing
 * directories but never wipes {@code data/} -- that is what {@link #wipeData}
 * is for.
 */
public final class VelaAvd {

    /** Verified layout: <code>&lt;avdHome&gt;/&lt;avdId&gt;.vvd</code>. */
    public static final String AVD_SUFFIX = ".vvd";
    /** Suffixes accepted when scanning, newest first. */
    static final String[] AVD_SUFFIXES = {".vvd", ".avd"};
    public static final String CONFIG_INI = "config.ini";
    public static final String AVD_CONF = "AVD.conf";
    public static final String USER_INI = "emulator-user.ini";
    public static final String HARDWARE_INI = "hardware-qemu.ini";
    public static final String SYSTEM_BIN = "vela_system.bin";
    public static final String DATA_BIN = "vela_data.bin";

    /** Guest files the launcher refuses to boot without. */
    static final String[] REQUIRED_IMAGE_FILES = {"nuttx", SYSTEM_BIN, DATA_BIN};

    private VelaAvd() {
    }

    /** A parsed AVD, as listed by {@link #listAll}. */
    public static final class Entry {
        public final File dir;
        public final String avdId;
        public final Map<String, String> config;

        Entry(File dir, String avdId, Map<String, String> config) {
            this.dir = dir;
            this.avdId = avdId;
            this.config = config;
        }

        public String skin() {
            return config.get("skin.name");
        }

        public String imageType() {
            String t = config.get("ide.image.type");
            return t == null ? "" : t;
        }

        public boolean imageInstalled() {
            String dir = config.get("image.sysdir.1");
            if (dir == null || dir.isEmpty()) {
                return false;
            }
            File d = new File(dir);
            for (String n : REQUIRED_IMAGE_FILES) {
                if (!new File(d, n).isFile()) {
                    return false;
                }
            }
            return true;
        }

        public Map<String, Object> toMap() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("avdId", avdId);
            m.put("path", dir.getAbsolutePath());
            m.put("display", config.get("avd.ini.displayname"));
            m.put("skin", skin());
            m.put("imageType", imageType());
            m.put("imageDir", config.get("image.sysdir.1"));
            m.put("imageInstalled", imageInstalled());
            m.put("cpuArch", config.get("hw.cpu.arch"));
            m.put("abi", config.get("abi.type"));
            m.put("ncore", parseInt(config.get("hw.cpu.ncore"), 1));
            m.put("ramSizeMb", parseRamMb(config.get("hw.ramSize")));
            m.put("density", parseInt(config.get("hw.lcd.density"), 160));
            int[] wh = parseSkin(config.get("skin"));
            m.put("width", wh[0] > 0 ? wh[0] : parseInt(config.get("hw.lcd.width"), 0));
            m.put("height", wh[1] > 0 ? wh[1] : parseInt(config.get("hw.lcd.height"), 0));
            m.put("shape", VelaDevices.shapeCode(config.get("hw.lcd.shape"),
                    parseInt(config.get("hw.lcd.shape"), 0)));
            m.put("dataBytes", VelaImageStore.dirSize(new File(dir, "data")));
            m.put("sizeBytes", VelaImageStore.dirSize(dir));
            return m;
        }
    }

    // ---------------------------------------------------------------- paths

    /**
     * {@code <avdHome>/<avdId>.vvd}. An existing {@code .avd} directory wins
     * over the canonical name, so a tree the AIoT IDE left behind is reused
     * instead of silently shadowed.
     */
    public static File directoryFor(String sdkRoot, String avdHome, String avdId) {
        String home = avdHome;
        if (home == null || home.isEmpty()) {
            home = sdkRoot == null || sdkRoot.isEmpty()
                    ? null : new File(sdkRoot, "vvd").getAbsolutePath();
        }
        String id = sanitize(avdId);
        File base = home == null ? new File(".").getAbsoluteFile() : new File(home);
        File canonical = new File(base, id + AVD_SUFFIX);
        if (canonical.isDirectory()) {
            return canonical;
        }
        for (String suffix : AVD_SUFFIXES) {
            if (suffix.equals(AVD_SUFFIX)) {
                continue;
            }
            File alt = new File(base, id + suffix);
            if (alt.isDirectory()) {
                return alt;
            }
        }
        return canonical;
    }

    public static File directoryFor(Context ctx, String avdId) {
        return directoryFor(VelaPaths.velaSdkDir(ctx).getAbsolutePath(),
                VelaPaths.velaVvdDir(ctx).getAbsolutePath(), avdId);
    }

    /**
     * Writes {@code <avdHome>/<id>.ini}, the pointer file the engine resolves an
     * AVD by ("no file x.ini in $ANDROID_AVD_HOME" and exit otherwise); the
     * {@code .vvd} directory alone is invisible to it. The AIoT IDE writes the
     * same file next to every AVD it creates.
     */
    public static void writePointerIni(File avdDir, String avdId) {
        File home = avdDir == null ? null : avdDir.getParentFile();
        if (home == null) {
            return;
        }
        String id = sanitize(avdId);
        File ini = new File(home, id + ".ini");
        VelaUtil.writeText(ini, "path=" + avdDir.getAbsolutePath() + "\n"
                + "path.rel=" + new File("avd", id + AVD_SUFFIX).getPath() + "\n");
        VelaLog.i("avd", "pointer ini -> " + ini.getAbsolutePath());
    }

    /** Where skins live after {@link VelaEngine} extracts them (note: plural). */
    public static String skinPath(String sdkRoot, String skin) {
        if (sdkRoot == null || sdkRoot.isEmpty()) {
            return "skins/" + skin;
        }
        return new File(new File(sdkRoot, "skins"), skin).getAbsolutePath();
    }

    /** {@code <sdk>/system-images/<flavor>/<type>} -- the unzipped image. */
    public static File nuttxImageDir(String sdkRoot, String flavor, String type) {
        File sdk = (sdkRoot == null || sdkRoot.isEmpty())
                ? new File(".vela/sdk") : new File(sdkRoot);
        return VelaImageStore.imageDir(sdk,
                flavor == null || flavor.isEmpty() ? type : flavor, type);
    }

    /**
     * AVD 用的镜像类型（config.ini 的 {@code ide.image.type}）。
     * 4.0 之前的镜像（vela-pre-*）装机/启动方式和 5.0 完全不同，装机前要先分辨。
     */
    public static String imageType(Context ctx, String avdId) {
        if (ctx == null || avdId == null || avdId.isEmpty()) {
            return "";
        }
        File ini = new File(VelaPaths.avdDirFor(ctx, avdId), "config.ini");
        String text = VelaUtil.slurpQuietly(ini);
        if (text == null) {
            return "";
        }
        for (String line : text.split("\n")) {
            int eq = line.indexOf('=');
            if (eq > 0 && line.substring(0, eq).trim().equalsIgnoreCase("ide.image.type")) {
                return line.substring(eq + 1).trim();
            }
        }
        return "";
    }

    // --------------------------------------------------------------- create

    /**
     * Writes a catalogue-driven AVD. Idempotent: re-running refreshes
     * config.ini and the directory skeleton without touching {@code data/}.
     */
    public static File create(Context ctx, VelaDevices.VelaDevice dev) throws IOException {
        if (dev == null) {
            throw new IOException("unknown device");
        }
        File sdkDir = VelaPaths.velaSdkDir(ctx);
        File imageDir = nuttxImageDir(sdkDir.getAbsolutePath(), dev.flavor, dev.imageType);
        if (!imageDir.isDirectory()) {
            // 同一种镜像可能被放在别的 flavor 目录下（watch/band 只是 IDE 的分目录习惯，
            // 内容是同一个 zip），按类型兜底找一遍，别让"明明装了"变成"未安装"。
            File alt = VelaImageStore.findImageElsewhere(sdkDir, dev.imageType);
            if (alt != null) {
                VelaLog.i("avd", "image " + dev.imageType + " 不在 " + imageDir
                        + "，改用 " + alt);
                imageDir = alt;
            }
        }
        if (!imageDir.isDirectory()) {
            throw new IOException("system image not installed: " + dev.imageType
                    + " (expected " + imageDir.getAbsolutePath() + ")");
        }
        List<String> missing = new ArrayList<>();
        for (String n : REQUIRED_IMAGE_FILES) {
            if (!new File(imageDir, n).isFile()) {
                missing.add(n);
            }
        }
        if (!missing.isEmpty()) {
            throw new IOException("system image incomplete, missing " + missing + " in " + imageDir);
        }

        File dir = directoryFor(ctx, dev.avdId);
        create(ctx, dev.avdId, dev, imageDir, dir);
        return dir;
    }

    /** Full form: explicit image directory and target AVD path. */
    public static File create(Context ctx, String avdId, VelaDevices.VelaDevice dev,
                              File imageDir, File avdDir) throws IOException {
        String id = sanitize(avdId == null || avdId.isEmpty()
                ? (dev == null ? "vela" : dev.avdId) : avdId);
        if (dev != null && !id.equals(dev.avdId)) {
            VelaLog.i("avd", "creating an AVD for " + dev.avdId + " under the id " + id);
        }

        File dir = avdDir != null ? avdDir : directoryFor(ctx, id);
        synchronized (VelaAvd.class) {
            if (!dir.isDirectory() && !dir.mkdirs() && !dir.isDirectory()) {
                throw new IOException("cannot create AVD dir " + dir.getAbsolutePath());
            }
            File data = new File(dir, "data");
            if (!data.isDirectory() && !data.mkdirs() && !data.isDirectory()) {
                throw new IOException("cannot create " + data.getAbsolutePath());
            }
            File share = new File(dir, "share");
            if (!share.isDirectory() && !share.mkdirs() && !share.isDirectory()) {
                throw new IOException("cannot create " + share.getAbsolutePath());
            }

            String sdkRoot = VelaPaths.velaSdkDir(ctx).getAbsolutePath();
            Map<String, String> cfg = buildConfig(id, dev, imageDir, sdkRoot);
            writeIni(new File(dir, CONFIG_INI), cfg,
                    "Vortex AVD configuration (managed file -- edits are lost on recreate)");
            VelaUtil.writeText(new File(dir, AVD_CONF),
                    "[config]\n"
                            + "targetAbi=" + cfg.get("abi.type") + "\n"
                            + "targetSdkVersion=5\n"
                            + "vendor=default\n"
                            + "type=wearable\n");

            Map<String, String> user = readIni(new File(dir, USER_INI));
            boolean freshUser = user.isEmpty();
            if (freshUser) {
                user = new LinkedHashMap<>();
                user.put("uuid", randomUuid());
            }
            user.put("window.x", "100");
            user.put("window.y", "100");
            writeIniPairwise(new File(dir, USER_INI), user, "emulator user settings");

            // config.ini may have been authored by the AIoT IDE with relative
            // sysdir entries; rewrite them so the launcher can resolve them.
            Map<String, String> written = readIni(new File(dir, CONFIG_INI));
            if (!written.isEmpty()) {
                boolean changed = false;
                String sysdir = cfg.get("image.sysdir.1");
                if (sysdir != null && !sysdir.equals(written.get("image.sysdir.1"))) {
                    written.put("image.sysdir.1", sysdir);
                    changed = true;
                }
                String spath = cfg.get("skin.path");
                if (spath != null && !spath.equals(written.get("skin.path"))) {
                    written.put("skin.path", spath);
                    changed = true;
                }
                if (changed) {
                    writeIni(new File(dir, CONFIG_INI), written,
                            "Vortex AVD configuration (managed file -- edits are lost on recreate)");
                }
            }

            copyImageFiles(imageDir, dir);
            writePointerIni(dir, id);
            VelaUtil.chmod755(dir);
            VelaLog.i("avd", "prepared " + dir.getAbsolutePath() + (freshUser ? " (new)" : " (refreshed)"));
            return dir;
        }
    }

    /** The verified key set. Empty {@code image.sysdir.2} is intentional. */
    private static Map<String, String> buildConfig(String id, VelaDevices.VelaDevice dev,
                                                   File imageDir, String sdkRoot) {
        String skin = dev == null ? "" : dev.skin;
        int w = dev == null ? 0 : dev.width;
        int h = dev == null ? 0 : dev.height;
        if (w <= 0 || h <= 0) {
            int[] wh = parseSkin(skin);
            w = wh[0];
            h = wh[1];
        }
        Map<String, String> c = new LinkedHashMap<>();
        c.put("AvdId", id);
        c.put("abi.type", dev != null && !dev.abi.isEmpty() ? dev.abi : "armeabi-v7a");
        c.put("avd.ini.displayname", displayName(id));
        c.put("avd.ini.encoding", "UTF-8");
        c.put("fastboot.forceColdBoot", "yes");
        c.put("fastboot.forceChosenSnapshotBoot", "no");
        c.put("fastboot.forceFastBoot", "no");
        c.put("hw.arc", "false");
        c.put("hw.audioInput", "yes");
        c.put("hw.battery", "yes");
        c.put("hw.camera.back", "None");
        c.put("hw.camera.front", "None");
        // NuttX guest is always arm32 (cortex-a8) whatever the host is.
        c.put("hw.cpu.arch", dev != null && !dev.cpuArch.isEmpty() ? dev.cpuArch : "arm");
        c.put("hw.cpu.ncore", String.valueOf(dev == null ? 2 : Math.max(1, dev.ncore)));
        c.put("hw.dPad", "no");
        c.put("hw.gps", "yes");
        c.put("hw.gpu.enabled", "no");
        c.put("hw.gpu.mode", "host");
        c.put("hw.initialOrientation", "Portrait");
        c.put("hw.keyboard", "yes");
        c.put("hw.lcd.density", String.valueOf(dev == null ? 160 : dev.density));
        // 模拟显示的 vsync。官方配置里没有这一项，而真机帧率恰好是 ~20fps ——
        // 怀疑 fork 的默认 vsync 就是 20Hz。显式写 60 做一次判定性实验：
        // 帧率跟着涨 = 之前是被显示刷新卡住的；没变化 = 是客机 UI 自己的节拍。
        c.put("hw.lcd.vsync", "60");
        c.put("hw.mainKeys", "no");
        // Plain megabytes: the launcher rejects "1024 MB" style values.
        c.put("hw.ramSize", String.valueOf(dev == null ? 1024 : Math.max(64, dev.ramSizeMb)));
        c.put("hw.sdCard", "no");
        c.put("hw.sensors.orientation", "yes");
        c.put("hw.trackBall", "no");
        c.put("image.sysdir.2", "");
        c.put("runtime.network.latency", "none");
        c.put("runtime.network.speed", "full");
        c.put("showDeviceFrame", "yes");
        c.put("skin.dynamic", "yes");
        c.put("skin.name", skin);
        c.put("skin.path", skinPath(sdkRoot, skin));
        // The launcher expects the shape name ("circle"/"rect"/"pill-shaped").
        c.put("hw.lcd.shape", dev == null || dev.shapeName.isEmpty() ? "rect" : dev.shapeName);
        c.put("ide.image.type", dev == null ? "" : dev.imageType);
        c.put("image.sysdir.1", new File(imageDir == null ? "" : imageDir.getAbsolutePath() + File.separator).getAbsolutePath());
        // The NuttX image carries its own rootfs; no cache partition is created.
        c.put("disk.cachePartition", "false");
        // 466x466 is a built-in launcher skin; every other panel needs the
        // explicit geometry next to skin.name/skin.path.
        boolean impliedBySkin = dev != null && dev.shape == 1 && w == 466 && h == 466;
        if (!impliedBySkin && w > 0 && h > 0) {
            c.put("hw.lcd.width", String.valueOf(w));
            c.put("hw.lcd.height", String.valueOf(h));
        }
        return c;
    }

    /** {@code nuttx} stays in the image dir; the two flash images are copied. */
    private static void copyImageFiles(File imageDir, File avdDir) throws IOException {
        for (String n : new String[]{SYSTEM_BIN, DATA_BIN}) {
            File src = new File(imageDir, n);
            File dst = new File(avdDir, n);
            long srcLen = src.length();
            if (dst.isFile() && dst.length() == srcLen) {
                continue;
            }
            if (dst.isFile() && srcLen == 0) {
                continue;
            }
            VelaLog.i("avd", "copying " + n + " (" + VelaUtil.formatBytes(srcLen) + ") into " + avdDir.getName());
            VelaUtil.copyFile(src, dst);
            VelaUtil.chmod755(dst);
        }
    }

    // ---------------------------------------------------------------- delete

    public static boolean deleteFile(File dir) {
        return dir != null && VelaUtil.deleteRecursive(dir);
    }

    public static boolean delete(Context ctx, String avdId) {
        return deleteFile(directoryFor(ctx, avdId));
    }

    /** Removes <code>data/</code> and the generated ini files; config survives. */
    public static boolean wipeData(Context ctx, String avdId) {
        File dir = directoryFor(ctx, avdId);
        if (!dir.isDirectory()) {
            return false;
        }
        VelaUtil.deleteRecursive(new File(dir, "data"));
        new File(dir, "data").mkdirs();
        new File(dir, "share").mkdirs();
        new File(dir, "hardware-qemu.ini").delete();
        new File(dir, DATA_BIN).delete();
        Map<String, String> cfg = readIni(new File(dir, CONFIG_INI));
        String sysdir = cfg.get("image.sysdir.1");
        if (sysdir != null && !sysdir.isEmpty()) {
            try {
                copyImageFiles(new File(sysdir), dir);
            } catch (IOException e) {
                VelaLog.w("avd", "wipe restock failed for " + avdId + ": " + e);
            }
        }
        return true;
    }

    /** Re-reads config.ini into an Entry, or null when the AVD is absent. */
    public static Entry byId(Context ctx, String avdId) {
        File dir = directoryFor(ctx, avdId);
        if (!dir.isDirectory()) {
            return null;
        }
        return new Entry(dir, avdId, readIni(new File(dir, CONFIG_INI)));
    }

    /** Rewrites image.sysdir.1 / ide.image.type -- after installing another image. */
    public static boolean pointAtImage(Context ctx, String avdId, File imageDir) {
        File cfg = new File(directoryFor(ctx, avdId), CONFIG_INI);
        Map<String, String> c = readIni(cfg);
        if (c.isEmpty()) {
            return false;
        }
        c.put("image.sysdir.1", new File(imageDir.getAbsolutePath() + File.separator).getAbsolutePath());
        c.put("ide.image.type", imageDir.getName());
        try {
            writeIni(cfg, c, "Vortex AVD configuration (managed file -- edits are lost on recreate)");
            copyImageFiles(imageDir, cfg.getParentFile());
            return true;
        } catch (IOException e) {
            VelaLog.e("avd", "pointAtImage failed: " + e);
            return false;
        }
    }

    // ------------------------------------------------------------------ list

    /** Every AVD under <code>ANDROID_AVD_HOME</code> with a readable config.ini. */
    public static List<Entry> listAll(Context ctx) {
        List<Entry> out = new ArrayList<>();
        File home = VelaPaths.velaVvdDir(ctx);
        File[] kids = home.listFiles();
        if (kids == null) {
            return out;
        }
        java.util.Arrays.sort(kids);
        for (File d : kids) {
            String n = d.getName();
            if (!d.isDirectory()) {
                continue;
            }
            String suffix = null;
            for (String cand : AVD_SUFFIXES) {
                if (n.endsWith(cand)) {
                    suffix = cand;
                    break;
                }
            }
            if (suffix == null) {
                continue;
            }
            Map<String, String> cfg = readIni(new File(d, CONFIG_INI));
            if (cfg.isEmpty() && !new File(d, AVD_CONF).isFile()) {
                continue;
            }
            String id = cfg.get("AvdId");
            if (id == null || id.isEmpty()) {
                id = n.substring(0, n.length() - suffix.length());
            }
            out.add(new Entry(d, id, cfg));
        }
        return out;
    }

    public static List<Map<String, Object>> listMaps(Context ctx) {
        List<Map<String, Object>> out = new ArrayList<>();
        for (Entry e : listAll(ctx)) {
            out.add(e.toMap());
        }
        return out;
    }

    // ----------------------------------------------------------------- ini io

    /** Flat ini reader used for config.ini / emulator-user.ini / AVD.conf. */
    public static Map<String, String> readIni(File f) {
        Map<String, String> out = new LinkedHashMap<>();
        if (f == null || !f.isFile()) {
            return out;
        }
        BufferedReader r = null;
        try {
            r = new BufferedReader(new InputStreamReader(new java.io.FileInputStream(f), "UTF-8"));
            String line;
            while ((line = r.readLine()) != null) {
                String s = line.trim();
                if (s.isEmpty() || s.startsWith("#") || s.startsWith(";") || s.startsWith("[")) {
                    continue;
                }
                int eq = s.indexOf('=');
                if (eq <= 0) {
                    continue;
                }
                out.put(s.substring(0, eq).trim(), unquote(s.substring(eq + 1).trim()));
            }
        } catch (IOException e) {
            VelaLog.w("avd", "cannot read " + f + ": " + e);
        } finally {
            VelaUtil.closeQuietly(r);
        }
        return out;
    }

    private static String unquote(String v) {
        if (v.length() >= 2 && (v.charAt(0) == '"' && v.charAt(v.length() - 1) == '"'
                || v.charAt(0) == '\'' && v.charAt(v.length() - 1) == '\'')) {
            return v.substring(1, v.length() - 1);
        }
        return v;
    }

    private static void writeIni(File f, Map<String, String> kv, String comment) throws IOException {
        writeIniPairwise(f, kv, comment);
    }

    private static void writeIniPairwise(File f, Map<String, String> kv, String comment)
            throws IOException {
        f.getParentFile().mkdirs();
        Writer w = new OutputStreamWriter(new FileOutputStream(f), "UTF-8");
        try {
            if (comment != null && !comment.isEmpty()) {
                w.write("# " + comment + "\n");
            }
            for (Map.Entry<String, String> e : kv.entrySet()) {
                w.write(e.getKey() + " = " + (e.getValue() == null ? "" : e.getValue()) + "\n");
            }
        } finally {
            w.close();
        }
    }

    // ------------------------------------------------------------- validation

    /** Missing required config.ini keys, for the diagnostics sheet. */
    public static List<String> validate(Context ctx, String avdId) {
        List<String> out = new ArrayList<>();
        File dir = directoryFor(ctx, avdId);
        if (!dir.isDirectory()) {
            out.add("avd directory missing: " + dir.getAbsolutePath());
            return out;
        }
        Map<String, String> cfg = readIni(new File(dir, CONFIG_INI));
        for (String key : new String[]{"AvdId", "image.sysdir.1", "skin.name", "skin.path",
                "hw.cpu.arch", "hw.ramSize", "hw.lcd.density"}) {
            String v = cfg.get(key);
            if (v == null || v.trim().isEmpty()) {
                out.add("config.ini missing " + key);
            }
        }
        String sysdir = cfg.get("image.sysdir.1");
        if (sysdir != null && !sysdir.isEmpty()) {
            File d = new File(sysdir);
            for (String n : REQUIRED_IMAGE_FILES) {
                if (!new File(d, n).isFile()) {
                    out.add("image file missing: " + new File(d, n).getName());
                }
            }
        }
        if (!new File(dir, "share").isDirectory()) {
            out.add("share/ missing");
        }
        if (!new File(dir, "data").isDirectory()) {
            out.add("data/ missing");
        }
        if (!new File(dir, SYSTEM_BIN).isFile()) {
            out.add(SYSTEM_BIN + " missing in AVD dir");
        }
        String spath = cfg.get("skin.path");
        if (spath != null && !spath.isEmpty() && !new File(spath).isDirectory()) {
            out.add("skin directory missing: " + spath + " (re-extract engine assets)");
        }
        return out;
    }

    /** A machine-readable dump of what the launcher will see. */
    public static Map<String, Object> inspect(Context ctx, String avdId) {
        File dir = directoryFor(ctx, avdId);
        Map<String, Object> m = new LinkedHashMap<>();
        m.put("avdId", avdId);
        m.put("path", dir.getAbsolutePath());
        m.put("exists", dir.isDirectory());
        m.put("config", readIni(new File(dir, CONFIG_INI)));
        m.put("user", readIni(new File(dir, USER_INI)));
        m.put("hardwareQemuGenerated", new File(dir, HARDWARE_INI).isFile());
        m.put("problems", validate(ctx, avdId));
        return m;
    }

    // ---------------------------------------------------------------- parsing

    static String sanitize(String raw) {
        String s = raw == null ? "vela" : raw.trim();
        if (s.isEmpty()) {
            s = "vela";
        }
        s = s.replaceAll("[^A-Za-z0-9._-]", "-");
        if (s.regionMatches(true, 0, "vela_", 0, 5)) {
            s = s.substring(5);
        }
        if (s.regionMatches(true, 0, "avd_", 0, 4)) {
            s = s.substring(4);
        }
        if (s.isEmpty()) {
            s = "vela";
        }
        return (s.startsWith("-") ? "avd-" : s) + (s.endsWith("-") ? "avd" : "");
    }

    static String displayName(String avdId) {
        String s = avdId.startsWith("miwear_") ? avdId.substring("miwear_".length()) : avdId;
        return "Vortex " + s.replace('_', ' ');
    }

    /** "466x466" / "192x572" -> {466,466}; anything else -> {0,0}. */
    static int[] parseSkin(String skin) {
        int[] out = {0, 0};
        if (skin == null) {
            return out;
        }
        String s = skin.toLowerCase(Locale.ROOT).replace("x", " ").trim();
        String[] parts = s.split("\\s+");
        if (parts.length == 2) {
            out[0] = parseInt(parts[0], 0);
            out[1] = parseInt(parts[1], 0);
        }
        return out;
    }

    static int parseInt(String s, int def) {
        try {
            return Integer.parseInt(s.trim());
        } catch (Exception e) {
            return def;
        }
    }

    /** config.ini wants "<n> MB"; readers want plain megabytes. */
    static int parseRamMb(String v) {
        if (v == null) {
            return 0;
        }
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < v.length(); i++) {
            char c = v.charAt(i);
            if (c >= '0' && c <= '9') {
                sb.append(c);
            } else if (sb.length() > 0) {
                break;
            }
        }
        return parseInt(sb.length() == 0 ? "0" : sb.toString(), 0);
    }

    static String randomUuid() {
        return UUID.randomUUID().toString();
    }

    /** config.ini as JSON, handy for logs. */
    public static String configAsJson(Context ctx, String avdId) {
        return new JSONObject(readIni(new File(directoryFor(ctx, avdId), CONFIG_INI))).toString();
    }
}
